### ISSUE TITLE
Fehler in der README

### ISSUE THREAD

**Issue by follow-the-tos** [ByRaudy/VelocitySystem#4]
Folgender Satz ist in deiner README zu finden:
> Dir ist jedoch nicht gestattet, das VelocitySystem zu froken & eine pull request zu starten.

In den [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users) steht jedoch folgendes:
> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

**Comment by ByRaudy** [comment]
Moin! Danke danke. Wusste nicht, das man es automatisch dazu freigibt. 

Ich habe es nun geändert.
